'use client'

import Image from 'next/image'
import { useState } from 'react'
import { DemoOutro } from '../_components/DemoOutro'

type MenuItem = { name: string; category: string; price: number; description: string }
const menu: MenuItem[] = [
  { name: 'Roti kip', category: 'Roti', price: 68, description: 'Kerrie, aardappel, kousenband en versgebakken roti' },
  { name: 'Roti vegetarisch', category: 'Vegetarisch', price: 55, description: 'Aardappel, kousenband, ei en groente' },
  { name: 'Nasi kip', category: 'Rijst & bami', price: 62, description: 'Gebakken rijst, kip, groente en gebakken ei' },
  { name: 'Moksi alesi', category: 'Rijst & bami', price: 72, description: 'Rijst met kip, zoutvlees, groente en zuur' },
  { name: 'Gebakken vis', category: 'Vis', price: 78, description: 'Krokante vis, friet en frisse komkommer' },
  { name: 'Gemberbier', category: 'Dranken', price: 18, description: 'Koud geserveerd, huisgemaakt' },
]
const categories = ['Populair', 'Roti', 'Rijst & bami', 'Vis', 'Vegetarisch', 'Dranken']

export default function WarungIndahPage() {
  const [category, setCategory] = useState('Populair')
  const [sent, setSent] = useState(false)
  const filtered = category === 'Populair' ? menu.filter(item => ['Roti kip', 'Moksi alesi', 'Gemberbier'].includes(item.name)) : menu.filter(item => item.category === category)

  return <div className="min-h-screen bg-[#f6f0e7] text-[#2b211c]" style={{ fontFamily: 'var(--font-demo-warm)' }}>
    <header className="border-b border-[#2b211c]/15"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#eten" className="text-xl font-semibold tracking-[-0.06em]">warung <span className="text-[#bd5f3f]">indah</span></a><nav className="hidden gap-6 text-sm md:flex"><a href="#menu">Menu</a><a href="#vinden">Open & locatie</a><a href="#reserveren">Reserveren</a></nav><a href="#reserveren" className="rounded-full bg-[#bd5f3f] px-4 py-2 text-sm font-semibold text-white">Reserveer</a></div></header>
    <main>
      <section id="eten" className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 pt-14 md:grid-cols-[0.9fr_1.1fr] md:items-center md:px-8 md:pb-24 md:pt-24"><div><p className="text-sm font-semibold text-[#bd5f3f]">Surinaams eten in Paramaribo</p><h1 className="mt-5 max-w-xl text-6xl font-semibold leading-[0.86] tracking-[-0.075em] md:text-8xl">Eet alsof je thuis bent.</h1><p className="mt-6 max-w-md text-lg leading-7 text-[#67574d]">Roti, nasi, bami en de gerechten waar je voor terugkomt. Vers uit de keuken, zonder omhaal.</p><div className="mt-8 flex flex-wrap items-center gap-5"><a href="#menu" className="rounded-full bg-[#2b211c] px-5 py-3 text-sm font-semibold text-white">Bekijk de kaart</a><span className="text-sm text-[#67574d]">Vandaag open 11:30-21:00</span></div></div><div className="relative aspect-[4/3] overflow-hidden rounded-[1.4rem] bg-[#dbc9b8]"><Image src="/demo-assets/warung-roti-table.webp" alt="Roti met kip, aardappel, kousenband en ingelegde komkommer" fill priority sizes="(min-width: 768px) 60vw, 100vw" className="object-cover" /></div></section>
      <section id="menu" className="border-y border-[#2b211c]/15 bg-[#fffaf3] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-7xl"><div className="mb-8 max-w-xl"><p className="text-sm font-semibold text-[#bd5f3f]">De kaart</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em] md:text-6xl">Kies waar je trek in hebt.</h2></div><div className="flex gap-2 overflow-x-auto border-b border-[#2b211c]/15 pb-4" role="tablist" aria-label="Menucategorieën">{categories.map(item => <button key={item} type="button" role="tab" aria-selected={category === item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-3 py-2 text-sm ${category === item ? 'border-[#2b211c] bg-[#2b211c] text-white' : 'border-[#2b211c]/20'}`}>{item}</button>)}</div><div className="mt-8 grid gap-x-10 md:grid-cols-2">{filtered.map(item => <article key={item.name} className="border-b border-[#2b211c]/15 py-5"><div className="flex justify-between gap-5"><h3 className="text-xl font-semibold">{item.name}</h3><span className="font-semibold">SRD {item.price}</span></div><p className="mt-2 text-sm text-[#67574d]">{item.description}</p></article>)}</div>{filtered.length === 0 && <p className="mt-8 text-sm text-[#67574d]">Geen gerechten in deze categorie.</p>}</div></section>
      <section id="vinden" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-2 md:px-8 md:py-24"><div className="relative aspect-[4/3] overflow-hidden bg-[#dbc9b8]"><Image src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&h=900&fit=crop&q=82" alt="Tafel met Surinaamse gerechten en drank" fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover" /></div><div className="self-center"><p className="text-sm font-semibold text-[#bd5f3f]">Open & locatie</p><h2 className="mt-3 text-4xl font-semibold leading-none tracking-[-0.06em] md:text-6xl">Loop binnen voor lunch of neem mee.</h2><dl className="mt-8 grid max-w-sm grid-cols-[auto_1fr] gap-x-8 gap-y-4 text-sm"><dt className="text-[#9b897e]">Adres</dt><dd>Voorbeeldlocatie, Paramaribo</dd><dt className="text-[#9b897e]">Open</dt><dd>Ma-zat / 11:30-21:00</dd><dt className="text-[#9b897e]">Bestellen</dt><dd>Demo via reservering hieronder</dd></dl></div></section>
      <section id="reserveren" className="bg-[#2b211c] px-5 py-16 text-[#f6f0e7] md:px-8 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[0.65fr_1.35fr]"><div><p className="text-sm font-semibold text-[#e99668]">Reserveren</p><h2 className="mt-4 text-5xl font-semibold leading-[0.9] tracking-[-0.06em] md:text-7xl">Tafel voor vanavond?</h2><p className="mt-5 max-w-sm text-[#c9bcb2]">Deze demo verstuurt niets. De flow laat zien hoe kort reserveren kan zijn.</p></div>{sent ? <div className="self-end border border-[#e99668] p-6"><p className="text-2xl font-semibold">Reservering bekeken.</p><p className="mt-2 text-[#c9bcb2]">Demo: in een echte website wordt nu contact opgenomen.</p><button type="button" onClick={() => setSent(false)} className="mt-6 text-sm font-semibold text-[#e99668] underline">Opnieuw</button></div> : <form className="grid gap-5" onSubmit={event => { event.preventDefault(); setSent(true) }}><div className="grid gap-5 sm:grid-cols-3"><label className="grid gap-2 text-sm">Datum<input required type="date" className="border-b border-white/30 bg-transparent px-0 py-3 text-white outline-none" /></label><label className="grid gap-2 text-sm">Tijd<select required className="border-b border-white/30 bg-[#2b211c] px-0 py-3 outline-none"><option value="">Kies</option><option>18:00</option><option>19:30</option><option>20:00</option></select></label><label className="grid gap-2 text-sm">Personen<select required className="border-b border-white/30 bg-[#2b211c] px-0 py-3 outline-none"><option value="">Kies</option><option>2</option><option>3-4</option><option>5+</option></select></label></div><label className="grid gap-2 text-sm">Naam<input required className="border-b border-white/30 bg-transparent px-0 py-3 outline-none" placeholder="Je naam" /></label><button type="submit" className="w-fit rounded-full bg-[#e99668] px-5 py-3 text-sm font-semibold text-[#2b211c]">Reservering bekijken</button></form>}</div></section>
    </main>
    <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-3 bg-[#f6f0e7] px-5 py-8 text-sm md:px-8"><span className="font-semibold">warung indah</span><span className="text-[#67574d]">Roti / rijst / bami / drank</span></footer>
    <DemoOutro />
  </div>
}
