'use client'

import Image from 'next/image'
import { useMemo, useState } from 'react'
import { DemoOutro } from '../_components/DemoOutro'

type Product = { name: string; category: string; price: number; size: string; image: string }
const products: Product[] = [
  { name: 'Linen overshirt', category: 'Jassen', price: 285, size: 'XS-L', image: '/demo-assets/bloom-collection.webp' },
  { name: 'Rib tank sand', category: 'Tops', price: 96, size: 'XS-XL', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&h=1100&fit=crop&q=82' },
  { name: 'Soft trouser olive', category: 'Broeken', price: 220, size: 'XS-L', image: 'https://images.unsplash.com/photo-1506629905607-d9d5d8d5c9e4?w=900&h=1100&fit=crop&q=82' },
  { name: 'Sundown scarf', category: 'Accessoires', price: 75, size: 'One size', image: 'https://images.unsplash.com/photo-1601924928378-7c6f8f6cfd6d?w=900&h=1100&fit=crop&q=82' },
]

export default function BloomBoutiquePage() {
  const [category, setCategory] = useState('Alles')
  const [cart, setCart] = useState<Product[]>([])
  const [selected, setSelected] = useState<Product | null>(null)
  const [cartOpen, setCartOpen] = useState(false)
  const shown = useMemo(() => category === 'Alles' ? products : products.filter(item => item.category === category), [category])
  const add = (product: Product) => setCart(items => items.some(item => item.name === product.name) ? items : [...items, product])

  return <div className="min-h-screen bg-[#f1f3f2] text-[#1c2623]" style={{ fontFamily: 'var(--font-demo-product)' }}>
    <header className="border-b border-[#1c2623]/15"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#new" className="text-2xl font-semibold tracking-[-0.08em]">bloom.</a><nav className="hidden gap-7 text-sm md:flex"><a href="#shop">Shop</a><a href="#story">Journal</a><a href="#story">Contact</a></nav><button type="button" onClick={() => setCartOpen(true)} className="text-sm font-semibold underline">Bag ({cart.length})</button></div></header>
    <main>
      <section id="new" className="mx-auto grid max-w-7xl gap-7 px-5 pb-14 pt-7 md:grid-cols-[0.8fr_1.2fr] md:items-end md:px-8 md:pb-24 md:pt-10"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#a34f35]">Tropical contemporary / drop 01</p><h1 className="mt-6 max-w-md text-6xl font-semibold leading-[0.88] tracking-[-0.075em] md:text-8xl">Clothes for warm days.</h1><p className="mt-6 max-w-sm text-lg leading-7 text-[#64716c]">Linnen, zachte jersey en kleur die werkt van ochtend tot avond.</p><a href="#shop" className="mt-8 inline-flex border-b border-[#a34f35] pb-2 text-sm font-semibold">Shop the collection <span className="ml-5">↘</span></a></div><div className="relative aspect-[4/3] overflow-hidden bg-[#d6ddd8]"><Image src="/demo-assets/bloom-collection.webp" alt="Linnen overshirt, rib top en terracotta sjaal uit de Bloom collectie" fill priority sizes="(min-width: 768px) 65vw, 100vw" className="object-cover" /></div></section>
      <section id="shop" className="border-y border-[#1c2623]/15 bg-[#e8ecea] px-5 py-14 md:px-8 md:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#a34f35]">The collection</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em] md:text-6xl">Pieces to live in.</h2></div><div className="flex gap-2 overflow-x-auto" aria-label="Productfilters">{['Alles', ...Array.from(new Set(products.map(item => item.category)))].map(item => <button key={item} type="button" onClick={() => setCategory(item)} className={`whitespace-nowrap border px-3 py-2 text-xs font-semibold ${category === item ? 'border-[#1c2623] bg-[#1c2623] text-white' : 'border-[#1c2623]/25'}`}>{item}</button>)}</div></div><div className="mt-10 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{shown.map(product => <article key={product.name} className="group"><button type="button" onClick={() => setSelected(product)} className="block w-full text-left"><div className="relative aspect-[4/5] overflow-hidden bg-[#d6ddd8]"><Image src={product.image} alt={product.name} fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.03]" /></div><div className="mt-3 flex justify-between gap-3 text-sm"><span>{product.name}</span><span>SRD {product.price}</span></div><p className="mt-1 text-xs text-[#75817c]">{product.category} / {product.size}</p></button><button type="button" onClick={() => add(product)} className="mt-4 text-xs font-semibold text-[#a34f35] underline">{cart.some(item => item.name === product.name) ? 'In bag' : 'Add to bag'}</button></article>)}</div></div></section>
      <section id="story" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-[0.7fr_1.3fr] md:px-8 md:py-24"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#a34f35]">The Bloom edit</p><h2 className="mt-4 max-w-sm text-4xl font-semibold leading-none tracking-[-0.06em] md:text-6xl">Less, but with a point.</h2></div><p className="max-w-md text-xl leading-8 text-[#64716c]">Een kleine garderobe voor een tropisch dagelijks leven. Combineerbare vormen, natuurlijke materialen en kleur die niet om aandacht hoeft te vragen.</p></section>
    </main>
    <footer className="border-t border-[#1c2623]/15 px-5 py-8 md:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 text-sm"><span className="font-semibold">bloom.</span><span className="text-[#64716c]">Shipping / returns / hello@bloom.example</span></div></footer>
    {(selected || cartOpen) && <div className="fixed inset-0 z-[70] bg-[#1c2623]/70 p-4 sm:p-8" role="dialog" aria-modal="true" aria-label={cartOpen ? 'Winkelwagen' : selected?.name}>{cartOpen ? <div className="mx-auto max-w-lg bg-[#f1f3f2] p-6"><div className="flex justify-between"><h2 className="text-2xl font-semibold">Your bag</h2><button type="button" onClick={() => setCartOpen(false)} className="text-sm underline">Sluiten</button></div>{cart.length === 0 ? <p className="mt-8 text-sm text-[#64716c]">Je bag is nog leeg.</p> : <div className="mt-7 grid gap-3">{cart.map(item => <div key={item.name} className="flex justify-between border-t border-[#1c2623]/15 pt-3 text-sm"><span>{item.name}</span><span>SRD {item.price}</span></div>)}<button type="button" onClick={() => setCartOpen(false)} className="mt-5 bg-[#1c2623] px-5 py-3 text-sm font-semibold text-white">Demo-checkout</button></div>}</div> : selected && <div className="mx-auto grid max-w-3xl gap-6 bg-[#f1f3f2] p-5 md:grid-cols-2 md:p-8"><div className="relative aspect-square bg-[#d6ddd8]"><Image src={selected.image} alt={selected.name} fill sizes="50vw" className="object-cover" /></div><div className="self-center"><p className="text-xs uppercase tracking-[0.2em] text-[#a34f35]">{selected.category}</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em]">{selected.name}</h2><p className="mt-4 text-lg">SRD {selected.price}</p><p className="mt-4 text-sm leading-6 text-[#64716c]">Zachte vorm, makkelijk te combineren. Maten {selected.size}.</p><button type="button" onClick={() => { add(selected); setSelected(null) }} className="mt-8 bg-[#1c2623] px-5 py-3 text-sm font-semibold text-white">Toevoegen aan bag</button><button type="button" onClick={() => setSelected(null)} className="ml-4 text-sm underline">Sluiten</button></div></div>}</div>}
    <DemoOutro />
  </div>
}
