'use client'

import Image from 'next/image'
import { useState } from 'react'
import { DemoOutro } from '../_components/DemoOutro'

const projects = [
  { name: 'Woning aan de Kwatta', type: 'Renovatie', place: 'Kwatta', status: 'Opgeleverd', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop&q=82' },
  { name: 'Kantoor aan de Tourtonnelaan', type: 'Interieurafbouw', place: 'Rainville', status: 'In uitvoering', image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=800&fit=crop&q=82' },
  { name: 'Houten huis Lelydorp', type: 'Nieuwbouw', place: 'Lelydorp', status: 'Ontwerp', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&h=800&fit=crop&q=82' },
  { name: 'Dak en veranda Zorg en Hoop', type: 'Renovatie', place: 'Zorg en Hoop', status: 'Opgeleverd', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop&q=82' },
]
const filters = ['Alle', 'Renovatie', 'Nieuwbouw', 'Interieurafbouw']

export default function KaderBouwPage() {
  const [filter, setFilter] = useState('Alle')
  const [submitted, setSubmitted] = useState(false)
  const visible = filter === 'Alle' ? projects : projects.filter((project) => project.type === filter)
  return <div className="min-h-screen bg-[#e9e6df] text-[#1b1d1b]" style={{ fontFamily: 'var(--font-demo-industrial)' }}>
    <header className="border-b border-[#1b1d1b]/20"><div className="mx-auto flex max-w-[90rem] items-center justify-between px-5 py-4 lg:px-10"><a href="#top" className="text-xl font-bold tracking-tight">KADER<span className="text-[#71833d]">BOUW</span></a><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#projecten">Projecten</a><a href="#werk">Werk</a><a href="#offerte">Offerte aanvragen</a></nav><a href="#offerte" className="border border-[#1b1d1b] px-3 py-2 text-xs font-bold uppercase tracking-[0.12em] hover:bg-[#1b1d1b] hover:text-[#e9e6df]">Start een gesprek</a></div></header>
    <main id="top"><section className="mx-auto grid max-w-[90rem] gap-8 px-5 pb-16 pt-10 md:grid-cols-[0.8fr_1.2fr] md:items-end md:px-10 md:pb-24 md:pt-16"><div><p className="mb-7 text-xs font-bold uppercase tracking-[0.2em] text-[#71833d]">Bouwbedrijf in Suriname</p><h1 className="max-w-[8ch] text-6xl font-semibold leading-[0.9] tracking-[-0.06em] sm:text-7xl lg:text-[8.5rem]">Ruimte die blijft staan.</h1><p className="mt-8 max-w-md text-lg leading-7 text-[#4f554d]">Van eerste schets tot nette oplevering. KaderBouw werkt aan woningen, zakelijke ruimtes en renovaties in en rond Paramaribo.</p><a href="#projecten" className="mt-8 inline-flex border-b-2 border-[#71833d] pb-2 text-sm font-bold">Bekijk het werk <span className="ml-5">↘</span></a></div><div className="relative aspect-[4/3] overflow-hidden bg-[#1b1d1b]"><Image src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&h=1200&fit=crop&q=82" alt="Betonnen gebouw in aanbouw met houten bekisting" fill priority className="object-cover" sizes="(min-width: 768px) 60vw, 100vw" /><div className="absolute bottom-0 left-0 border-t border-r border-white/40 bg-[#1b1d1b]/85 px-4 py-3 text-xs text-white">Woningbouw / Kwatta</div></div></section>
      <section id="projecten" className="border-y border-[#1b1d1b]/20 bg-[#d6d4cd] px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-[90rem]"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#71833d]">Projecten</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] md:text-6xl">Het werk spreekt.</h2></div><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`border px-3 py-2 text-xs font-bold ${filter === item ? 'border-[#1b1d1b] bg-[#1b1d1b] text-white' : 'border-[#1b1d1b]/30 hover:border-[#1b1d1b]'}`} aria-pressed={filter === item}>{item}</button>)}</div></div><div className="grid gap-x-6 gap-y-12 md:grid-cols-2">{visible.map((project, index) => <article key={project.name} className={index % 2 === 1 ? 'md:mt-20' : undefined}><div className="relative aspect-[4/3] overflow-hidden bg-[#b7b6ae]"><Image src={project.image} alt={`${project.name}, ${project.type}`} fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.03]" /></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-3 border-t border-[#1b1d1b]/30 pt-3 text-sm"><div><h3 className="font-semibold">{project.name}</h3><p className="mt-1 text-[#5a5e56]">{project.type} / {project.place}</p></div><span className="text-[#71833d]">{project.status}</span></div></article>)}</div>{visible.length === 0 && <p className="border-t border-[#1b1d1b]/30 pt-6 text-[#5a5e56]">Geen projecten in deze categorie.</p>}</div></section>
      <section id="werk" className="mx-auto grid max-w-[90rem] gap-10 px-5 py-16 md:grid-cols-[0.8fr_1.2fr] md:px-10 md:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#71833d]">Waar we aan werken</p><h2 className="mt-4 max-w-sm text-4xl font-semibold leading-none tracking-[-0.05em] md:text-6xl">Praktisch, van fundering tot afwerking.</h2></div><div className="divide-y divide-[#1b1d1b]/20 border-y border-[#1b1d1b]/20">{['Renovatie', 'Nieuwbouw', 'Interieurafbouw', 'Zakelijke projecten'].map((item, index) => <div key={item} className="flex items-center justify-between py-5 text-xl"><span>{item}</span><span className="text-sm text-[#71833d]">0{index + 1}</span></div>)}</div></section>
      <section id="offerte" className="bg-[#1b1d1b] px-5 py-16 text-[#e9e6df] md:px-10 md:py-24"><div className="mx-auto grid max-w-[90rem] gap-12 md:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#a8be5b]">Offerte aanvragen</p><h2 className="mt-4 max-w-sm text-5xl font-semibold leading-[0.92] tracking-[-0.05em] md:text-7xl">Vertel wat er moet gebeuren.</h2><p className="mt-6 max-w-sm text-[#b4b7ad]">Een eerste omschrijving is genoeg. Dit formulier is een demo en verstuurt niets.</p></div>{submitted ? <div className="self-end border border-[#a8be5b] p-6"><p className="text-xl font-semibold">Aanvraag klaar voor verzending.</p><p className="mt-2 text-[#b4b7ad]">Demo: in een echte website gaat dit naar het bouwbedrijf.</p><button type="button" onClick={() => setSubmitted(false)} className="mt-6 border-b border-[#a8be5b] pb-1 text-sm font-bold text-[#a8be5b]">Nieuwe aanvraag</button></div> : <form className="grid gap-6" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><div className="grid gap-6 sm:grid-cols-2"><label className="grid gap-2 text-sm">Naam<input required className="border-b border-white/35 bg-transparent px-0 py-3 outline-none focus:border-[#a8be5b]" placeholder="Je naam" /></label><label className="grid gap-2 text-sm">Telefoon<input required className="border-b border-white/35 bg-transparent px-0 py-3 outline-none focus:border-[#a8be5b]" placeholder="597 ..." /></label></div><div className="grid gap-6 sm:grid-cols-2"><label className="grid gap-2 text-sm">Type project<select required className="border-b border-white/35 bg-[#1b1d1b] px-0 py-3 outline-none focus:border-[#a8be5b]"><option value="">Kies een richting</option><option>Renovatie</option><option>Nieuwbouw</option><option>Interieurafbouw</option></select></label><label className="grid gap-2 text-sm">District of locatie<input className="border-b border-white/35 bg-transparent px-0 py-3 outline-none focus:border-[#a8be5b]" placeholder="Bijvoorbeeld Wanica" /></label></div><label className="grid gap-2 text-sm">Korte omschrijving<textarea required rows={3} className="resize-y border-b border-white/35 bg-transparent px-0 py-3 outline-none focus:border-[#a8be5b]" placeholder="Wat wil je bouwen of aanpassen?" /></label><button type="submit" className="w-fit border border-[#a8be5b] px-5 py-3 text-sm font-bold text-[#a8be5b] hover:bg-[#a8be5b] hover:text-[#1b1d1b]">Aanvraag bekijken <span className="ml-4">↗</span></button></form>}</div></section></main><footer className="mx-auto flex max-w-[90rem] flex-wrap justify-between gap-4 bg-[#e9e6df] px-5 py-8 text-sm md:px-10"><span className="font-bold">KADERBOUW</span><span className="text-[#5a5e56]">Projecten / werk / offerte</span></footer><DemoOutro />
  </div>
}
