'use client'

import { useState } from 'react'
import { DemoOutro } from '../_components/DemoOutro'

type Site = { name: string; status: string; cpu: string; memory: string; deploy: string }
const sites: Site[] = [
  { name: 'kaderbouw.example', status: 'Online', cpu: '18%', memory: '41%', deploy: '12 min geleden' },
  { name: 'shopplaza.example', status: 'Online', cpu: '7%', memory: '29%', deploy: 'Gisteren' },
  { name: 'savana.example', status: 'Onderhoud', cpu: '0%', memory: '12%', deploy: '3 dagen geleden' },
]
const backups = [
  { date: '22 sep 2026 / 03:00', size: '2.4 GB', status: 'Klaar' },
  { date: '21 sep 2026 / 03:00', size: '2.4 GB', status: 'Klaar' },
  { date: '20 sep 2026 / 03:00', size: '2.3 GB', status: 'Klaar' },
]

export default function HostingPanelPage() {
  const [view, setView] = useState('Sites')
  const [backup, setBackup] = useState(false)
  const [activeSite, setActiveSite] = useState(sites[0])

  return <div className="min-h-screen bg-[#f2f4f3] text-[#1d2a27]" style={{ fontFamily: 'var(--font-demo-product)' }}>
    <header className="border-b border-[#1d2a27]/15 bg-[#17241f] text-[#ecf2ed]"><div className="mx-auto flex max-w-[90rem] items-center justify-between px-4 py-4 md:px-8"><a href="#sites" className="font-mono text-sm font-medium tracking-[0.12em]">HOST / PANEL</a><span className="font-mono text-xs text-[#a7b9ad]">workspace: demo</span></div></header>
    <main id="sites" className="mx-auto grid max-w-[90rem] gap-8 px-4 py-6 md:px-8 md:py-10 lg:grid-cols-[12rem_1fr]">
      <aside><p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-[#74867d]">Manage</p><nav className="mt-4 grid gap-1">{['Sites', 'Domains', 'Backups', 'Usage', 'Logs'].map(item => <button type="button" key={item} onClick={() => setView(item)} className={`border-l-2 px-3 py-2 text-left text-sm ${view === item ? 'border-[#277e62] bg-[#e0ece5] font-semibold text-[#21634f]' : 'border-transparent text-[#74867d]'}`}>{item}</button>)}</nav><div className="mt-10 border-t border-[#1d2a27]/15 pt-4 text-xs leading-5 text-[#74867d]">Demo-omgeving.<br />Acties hebben geen extern effect.</div></aside>
      <section>
        {view === 'Sites' && <><div className="flex flex-wrap items-end justify-between gap-4 border-b border-[#1d2a27]/15 pb-6"><div><p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-[#277e62]">Sites</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.06em] md:text-6xl">Keep the lights on.</h1></div><button type="button" onClick={() => setBackup(true)} className="border border-[#1d2a27]/25 bg-white px-4 py-2.5 text-sm font-semibold">Create backup</button></div><div className="mt-8 grid gap-3">{sites.map(site => <button key={site.name} type="button" onClick={() => setActiveSite(site)} className={`grid gap-4 border bg-white p-5 text-left md:grid-cols-[1.4fr_0.5fr_0.45fr_0.45fr_0.7fr] md:items-center ${activeSite.name === site.name ? 'border-[#277e62]' : 'border-[#1d2a27]/15'}`}><span className="font-medium">{site.name}</span><span className="flex items-center gap-2 text-sm text-[#277e62]"><i className="h-2 w-2 rounded-full bg-[#277e62]" />{site.status}</span><span className="font-mono text-xs text-[#74867d]">CPU {site.cpu}</span><span className="font-mono text-xs text-[#74867d]">RAM {site.memory}</span><span className="text-xs text-[#74867d]">Deploy {site.deploy}</span></button>)}</div><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="border border-[#1d2a27]/15 bg-[#e0ece5] p-5"><p className="font-mono text-xs text-[#74867d]">Selected site</p><p className="mt-3 font-semibold">{activeSite.name}</p><p className="mt-1 text-sm text-[#74867d]">Last deploy {activeSite.deploy}</p></div><div className="border border-[#1d2a27]/15 bg-white p-5"><p className="font-mono text-xs text-[#74867d]">SSL</p><p className="mt-3 font-semibold text-[#277e62]">Active</p><p className="mt-1 text-sm text-[#74867d]">Renews automatically</p></div><div className="border border-[#1d2a27]/15 bg-white p-5"><p className="font-mono text-xs text-[#74867d]">Next backup</p><p className="mt-3 font-semibold">Tonight / 03:00</p><p className="mt-1 text-sm text-[#74867d]">Daily retention: 7</p></div></div></>}
        {view === 'Backups' && <><div className="flex items-end justify-between border-b border-[#1d2a27]/15 pb-6"><div><p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-[#277e62]">Backups</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.06em]">Restore points.</h1></div><button type="button" onClick={() => setBackup(true)} className="bg-[#277e62] px-4 py-2.5 text-sm font-semibold text-white">Run backup</button></div><div className="mt-8 border border-[#1d2a27]/15 bg-white">{backups.map(item => <div key={item.date} className="grid gap-3 border-b border-[#1d2a27]/10 p-5 last:border-0 md:grid-cols-[1.2fr_0.5fr_0.5fr_auto] md:items-center"><span className="font-mono text-sm">{item.date}</span><span className="text-sm text-[#74867d]">{item.size}</span><span className="text-sm text-[#277e62]">{item.status}</span><button type="button" onClick={() => setBackup(true)} className="w-fit text-sm font-semibold underline">Restore</button></div>)}</div></>}
        {view === 'Usage' && <><div className="border-b border-[#1d2a27]/15 pb-6"><p className="font-mono text-[0.65rem] uppercase tracking-[0.16em] text-[#277e62]">Usage</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.06em]">Capacity in view.</h1></div><div className="mt-8 grid gap-4 md:grid-cols-2">{[['Storage', '41 GB', 'of 100 GB', 41], ['Bandwidth', '184 GB', 'of 500 GB', 37], ['Database', '1.8 GB', 'of 10 GB', 18], ['Mailboxes', '7', 'of 25', 28]].map(([label, value, meta, width]) => <div key={label as string} className="border border-[#1d2a27]/15 bg-white p-5"><div className="flex items-baseline justify-between"><span className="font-semibold">{label}</span><span className="font-mono text-sm">{value}</span></div><div className="mt-5 h-1 bg-[#e1e8e4]"><div className="h-1 bg-[#277e62]" style={{ width: `${width}%` }} /></div><p className="mt-3 text-xs text-[#74867d]">{meta}</p></div>)}</div></>}
        {view === 'Domains' && <div className="border-b border-[#1d2a27]/15 pb-6"><p className="font-mono text-[0.65em] uppercase tracking-[0.16em] text-[#277e62]">Domains</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.06em]">Names and certificates.</h1><div className="mt-8 border border-[#1d2a27]/15 bg-white p-5 text-sm"><div className="flex justify-between"><span>kaderbouw.example</span><span className="text-[#277e62]">SSL active</span></div></div></div>}
        {view === 'Logs' && <div className="border border-[#1d2a27]/15 bg-[#17241f] p-5 font-mono text-xs leading-7 text-[#bcd0c2]"><div className="mb-4 flex justify-between border-b border-white/10 pb-3 text-[#ecf2ed]"><span>deploy.log / {activeSite.name}</span><span>demo tail</span></div><p>03:14:02 build completed</p><p>03:14:06 assets uploaded</p><p>03:14:07 health check passed</p><p>03:14:08 deployment marked ready</p></div>}
      </section>
    </main>
    {backup && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#17241f]/60 p-5" role="dialog" aria-modal="true" aria-label="Demo backup bevestigen"><div className="w-full max-w-md bg-white p-6"><h2 className="text-xl font-semibold">Run a demo backup?</h2><p className="mt-3 text-sm leading-6 text-[#74867d]">This action is simulated. No files will be changed.</p><div className="mt-6 flex gap-3"><button type="button" onClick={() => setBackup(false)} className="bg-[#277e62] px-4 py-2.5 text-sm font-semibold text-white">Bevestigen</button><button type="button" onClick={() => setBackup(false)} className="border border-[#1d2a27]/25 px-4 py-2.5 text-sm">Annuleren</button></div></div></div>}
    <DemoOutro />
  </div>
}
