'use client'

import Image from 'next/image'
import { useState } from 'react'
import { DemoOutro } from '../_components/DemoOutro'

const applications = [
  { title: 'Koffiezak', note: 'Mat charcoal folie, warm cream label', image: '/demo-assets/savana-packaging.webp' },
  { title: 'Koffiebeker', note: 'Donkergroen keramiek, rustige signatuur', image: '/demo-assets/savana-cup.jpg' },
  { title: 'Tafelkaart', note: 'Aandacht voor materiaal en witruimte', image: '/demo-assets/savana-menu.jpg' },
]

export default function SavanaCoffeePage() {
  const [tab, setTab] = useState('systeem')
  const tabs = ['systeem', 'verpakking', 'stem']
  return <div className="min-h-screen bg-[#e9e1d3] text-[#17241e]" style={{ fontFamily: 'var(--font-demo-warm)' }}>
    <header className="border-b border-[#17241e]/20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="#top" className="flex items-center gap-3 text-lg font-semibold"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#17241e] text-sm">S</span> SAVANA</a><nav className="flex gap-5 text-xs font-semibold uppercase tracking-[0.14em]"><a href="#world">Brand world</a><a href="#applications">Applications</a></nav></div></header>
    <main>
      <section id="top" className="mx-auto grid max-w-7xl gap-12 px-5 pb-16 pt-14 md:grid-cols-[0.85fr_1.15fr] md:items-center md:px-8 md:pb-24 md:pt-24"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#557047]">Brand identity concept</p><h1 className="mt-6 max-w-xl text-6xl font-semibold leading-[0.88] tracking-[-0.07em] md:text-8xl">Coffee with a sense of place.</h1><p className="mt-7 max-w-md text-lg leading-7 text-[#56645a]">Savana is a fictional coffee label built around slow mornings, deep greens and a mark that feels at home on paper, ceramic and screen.</p><a href="#world" className="mt-8 inline-flex border-b border-[#557047] pb-2 text-sm font-semibold">View the brand world <span className="ml-5">↘</span></a></div><div className="relative aspect-[4/3] overflow-hidden bg-[#31452f]"><Image src="/demo-assets/savana-packaging.webp" alt="Savana Coffee verpakking, kop en bonen op donkergroene tafel" fill priority sizes="(min-width: 768px) 60vw, 100vw" className="object-cover" /></div></section>
      <section id="world" className="border-y border-[#17241e]/20 bg-[#31452f] px-5 py-16 text-[#e9e1d3] md:px-8 md:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2 border-b border-[#e9e1d3]/25 pb-4" role="tablist">{tabs.map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`border px-3 py-2 text-xs font-semibold uppercase tracking-[0.16em] ${tab === item ? 'border-[#e9e1d3] bg-[#e9e1d3] text-[#31452f]' : 'border-[#e9e1d3]/25 text-[#e9e1d3]/65'}`}>{item}</button>)}</div>{tab === 'systeem' && <div className="grid gap-12 pt-12 md:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm text-[#bccbb8]">The mark</p><div className="mt-5 flex items-center gap-5"><div className="grid h-28 w-28 place-items-center rounded-full border-4 border-[#e9e1d3] text-6xl">S</div><div className="text-4xl font-semibold tracking-[-0.08em]">SAVANA</div></div></div><div><p className="max-w-lg text-3xl leading-tight tracking-[-0.05em] md:text-5xl">A simple arch suggests a sun, a horizon and a cup without drawing any of them.</p><div className="mt-10 grid grid-cols-3 gap-3"><div className="h-20 bg-[#e9e1d3]" /><div className="h-20 bg-[#b7c49f]" /><div className="h-20 bg-[#9a6a46]" /></div></div></div>}{tab === 'verpakking' && <div className="grid gap-10 pt-12 md:grid-cols-2"><div><p className="text-3xl leading-tight tracking-[-0.05em]">Material first. Mark second.</p><p className="mt-4 max-w-sm text-[#bccbb8]">The system is designed to hold its shape when the bag is the only thing on a shelf.</p></div><div className="relative aspect-[4/3] overflow-hidden"><Image src="/demo-assets/savana-packaging.webp" alt="Savana Coffee verpakking in groene setting" fill sizes="50vw" className="object-cover" /></div></div>}{tab === 'stem' && <div className="grid gap-10 pt-12 md:grid-cols-[0.7fr_1.3fr]"><p className="text-3xl leading-tight tracking-[-0.05em]">Warm, direct, grounded.</p><div className="grid border-t border-[#e9e1d3]/25"><div className="border-b border-[#e9e1d3]/25 py-5 text-lg">Say what the cup tastes like.</div><div className="border-b border-[#e9e1d3]/25 py-5 text-lg">Leave the romance to the morning.</div><div className="border-b border-[#e9e1d3]/25 py-5 text-lg">Use fewer words, better ones.</div></div></div>}</div></section>
      <section id="applications" className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="mb-10 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#557047]">In the world</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em] md:text-6xl">A brand that travels.</h2></div><span className="text-sm text-[#56645a]">03 applications</span></div><div className="grid gap-6 md:grid-cols-3">{applications.map(item => <article key={item.title}><div className="relative aspect-[4/3] overflow-hidden bg-[#d3c9b9]"><Image src={item.image} alt={`${item.title} toepassing voor Savana Coffee`} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.03]" /></div><h3 className="mt-4 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-[#56645a]">{item.note}</p></article>)}</div></section>
    </main>
    <footer className="border-t border-[#17241e]/20 px-5 py-8 md:px-8"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 text-sm"><span className="font-semibold">SAVANA COFFEE</span><span className="text-[#56645a]">Brand identity / packaging / voice</span></div></footer>
    <DemoOutro />
  </div>
}
